version: "3.9"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ".:/app"
    restart: always
    networks:
      - network
    links:
      - tarantool

  tarantool:
    image: tarantool/tarantool:latest
    environment:
      - TARANTOOL_USER_NAME=${TARANTOOL_USER_NAME}
      - TARANTOOL_USER_PASSWORD=${TARANTOOL_USER_PASSWORD}
      - TARANTOOL_PORT=${TARANTOOL_PORT}
      - TARANTOOL_PROMETHEUS_DEFAULT_METRICS_PORT=${TARANTOOL_PROMETHEUS_DEFAULT_METRICS_PORT}
    volumes:
      - ".data/tarantool:/var/lib/tarantool"
    restart: always
    networks:
      - network
    ports:
      - "3301:3301"

networks:
  network:
    driver: bridge
